[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback so router refreshes don't 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Basic security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
